cluster:
  name: cluster
  privateKey: cluster-key
machines:
  - count: 1
    spec:
      image: quay.io/footloose/ubuntu16.04
      name: node%d
      portMappings:
        - containerPort: 22
        - containerPort: 8000
          hostPort: 8000
      privileged: true

