[[kubernetes_test_plugin]]
= The Kubernetes flavor of the Platform Test Plugin

The Kubernetes flavor of the Platform Test Gradle plugin manages the lifecycle of a Kubernetes cluster to set up systems under test for E2E testing

[[sec:kubernetes_test_tasks]]
== Tasks

The plugin intends to augment Gradle’s built-in test task by providing a task called `deployToKubernetes` that will set up
 a Kubernetes cluster, deploying a workload on it and waiting for some probe.

To cleanup the container enclosing the Kubernetes cluster a task called `cleanupKubernetes` will have to be called.

To do that, it uses link:url[k3d, https://github.com/rancher/K3d], a tool that runs link:url[K3s, https://k3s.io/], a lightweight Kubernetes distro, in Docker.

This implies that no dependencies are required on the executing machine, except for Docker itself.

[[sec:kubernetes_test_extension]]
=== Extension

[source,kotlin]
----
kubernetes {
    deployment {
        manifests = files("first_manifest.yaml", "second_manifest.yaml")
        script = file("/installationDir/install.sh")
        chart {
            repo = "chartmuseum"
            name = "mychart"
            version = "0.1.0"
            release = "mychart"
            user = "myUser"
            password = "myPwd"
        }
        edge {
            name = "nginx"
            port = 8081
        }
    }
    namespace = "kubernetes-test-plugin"
    k3dVersion = "v4.0.0"
    probe {
        retries = 2
        delay = 20
        port = 8082
        path = "/missing"
        status = 404
    }
}
----

* deployment - where the deployment materials reside. There are two mutually exclusive mechanisms:
** manifests - yaml files to be deployed against the kubernetes cluster.
** script - deployment script that could reference to arbitrary kubectl commands and not only raw yaml manifests.
** chart - helm chart information to be deployed as a helm release
*** repo - name of the repo
*** name - name of the chart
*** version - version of the chart
*** release - name of the release to be created
*** user - user when the helm repo is under basic authentication
*** password - password when the helm repo is under basic authentication
** edge - information about your edge service that will be automatically exposed by an Ingress.
*** name - name of your service. By default, `edge`.
*** port - http port of your service, https is not yet supported. By default, 80.
* namespace - namespace to deploy the workloads. It will be created by the plugin. By default, it uses the `default` namespace that doesn't require creation.
* k3dVersion - By default "v4.0.0"
* probe - for above's example, the plugin won't give control to the test task until http://localhost:8082/missing would return 404.
It will retry twice, with a 120 seconds delay.
** retries - by default 20
** delay - in seconds. By default 10 seconds.
** port - an ingress controller will be open on this configured port, i.e. localhost:port will be accessible from the host. By default 8081.
** path - where to check that the platform is ready to serve, aka ready to be tested. By default "/". N.b the leading slash is expected
** status - the acceptable status code return by the probe. By default 200

[[sec:kubernetes_test_technical_details]]
== Technical details

=== Networking

K3d runs a Kubernetes cluster in Docker. K3d itself is a command line that can be run in Docker too. The plugin uses both mechanisms, therefore, it's portable and not require
any previous dependencies installed on your machine, except Docker, of course.

The plugin assumes that you deploy a service listening on http 80 called edge (port and name configurables). That edge port will serve as an entrypoint for your platform.
Finally, when creating the k3d cluster, it will be stated that `probe/port` needs to be open in the docker container.

All of this network madness allows the following flow:

curl localhost:8081 -> Docker rancher/k3d-proxy container exposes 8081 -> Ingress controller exposes the Kubernetes cluster on 8081 and redirects to the edge service in port 80

=== Persistence

K3d install a local path provisioner called `local-path`. If your workloads deploy persistent volumes, and you don't
want to provision your own one, fill `local-path` as storage class on your manifests.

[[sec:kubernetes_test_notes]]
== Notes

=== Docker Desktop for Mac

When using Docker Desktop for Mac bear in mind that the default memory limit for containers is
2GB so it might be insufficient for your deployments.